### ISSUE TITLE
Browser finder suggestion

### ISSUE THREAD

**Issue by griffith1deady** [HapticX/happyx-native#1]
What about make 'define browser:any'? It could be very useful, because if you wanna use HappyX-Native for app production, like game launcher or other: you still don't know what browser use your user. The same idea i see in WebUI, but it's C library and Nim wrapper very buggy.
Thank's for your hard work!

**Comment by Ethosa** [comment]
I think that `-d:browser:any` is bad idea, BUT making any browser by the default is good idea!
I'll see what I can do.

**Comment by griffith1deady** [comment]
> I think that `-d:browser:any` is bad idea, BUT making any browser by the default is good idea! I'll see what I can do.

why do you think that it bad idea? you talking about bad start time, or browser specific html/js/etc? if so, I don't really understand how to proceed then in the case of offloading the application to users.

and about performance (start time) if you mean it, you always can prioritise find browser queue by statistic of high user-usage by OS. btw in webui it work good

**Comment by Ethosa** [comment]
nope, I mean that `happyx-native` should find the default browser that user uses if not `-d:chrome/yandex/edge/...` was passed

**Comment by griffith1deady** [comment]
oh, sorry then. i thought you didn't like the idea as a whole. i agree with you, but just offered an abstract solution that i've seen in other implementations. anyway, thanks for your work!
